# Generated by Django 4.1.6 on 2023-03-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(
                        default="Company Name", max_length=100, unique=True
                    ),
                ),
                ("company_active", models.BooleanField(default=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[("PH", "Pharmacy"), ("DH", "Digital Health")],
                        default="DH",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                ("pharmacy_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "pharmacy_type",
                    models.CharField(
                        choices=[
                            ("VP", "Virtual Pharmacy"),
                            ("DT", "Digital Therapeutics"),
                            ("CDM", "Chronic Disease Management"),
                            ("PPS", "Personalized Pharmacy Services"),
                            ("PG", "Pharmacogenomics"),
                            ("VS", "Vitamins & Supplements"),
                            ("HLTM", "Home Lab Testing & Monitoring"),
                            ("HP", "Hospital Pharmacy"),
                            ("NP", "Novel Pharma"),
                            ("DTCPS", "DTC Pharmacy Services"),
                            ("PSWE", "Pharm Services Workflow Expansion"),
                            ("PM", "Pharmacy Media"),
                        ],
                        max_length=100,
                    ),
                ),
                ("pharmacy_logo", models.TextField(default="")),
                ("pharmacy_url", models.URLField(default="")),
                ("pharmacy_description", models.TextField(default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharmd.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Digital_Health",
            fields=[
                (
                    "digital_health_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "digital_health_type",
                    models.CharField(
                        choices=[
                            ("MH", "Mental Health"),
                            ("G", "Genetics"),
                            ("PDACN", "Provider Directories & Care Navigation"),
                            ("HVIC", "Hybrid Virtual In-Person Care"),
                            ("DT", "Digital Therapeutics"),
                            ("BAP", "Billing & Payments"),
                            ("AD", "App Deployment"),
                            ("SMD", "Screening, Monitoring, Diagnostics"),
                            ("DIA", "Data Integration & Analytics"),
                            ("CI", "Clinical Intelligence"),
                            ("HHT", "Home Health Tech"),
                            ("VC", "Virtual Care"),
                            ("PE", "Patient Engagement"),
                            ("CCC", "Care Coordination & Collaboration"),
                            ("WDA", "Workflow Digitization & Automation"),
                            ("CAI", "Computer-Aided Imaging"),
                            ("CT", "Clinical Trials"),
                        ],
                        max_length=100,
                    ),
                ),
                ("digital_health_logo", models.TextField(default="")),
                ("digital_health_url", models.URLField(default="")),
                ("digital_health_description", models.TextField(default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharmd.company"
                    ),
                ),
            ],
        ),
    ]
